#cloud-config
package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apache2-utils
  - git
  - docker-ce
  - docker-ce-cli
  - containerd.io

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

write_files:
  - path: /root/install-k8s.sh
    permissions: '0755'
    content: |
      {{ k8s_script }}
  
  - path: /root/deploy-seats-booking.sh
    permissions: '0755'
    content: |
      {{ deploy_script }}
  
  - path: /root/load-test.sh
    permissions: '0755'
    content: |
      {{ load_test_script }}

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - /root/install-k8s.sh
  - sleep 60
  - /root/deploy-seats-booking.sh

final_message: "Kubernetes cluster setup is complete. Please check /root/app-info.txt for application URLs." 