#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - docker.io

runcmd:
  - systemctl enable docker
  - systemctl start docker

  - docker network create app-network

  - >
    docker run -d --name postgres
    --network app-network 
    -e POSTGRES_USER=devops 
    -e POSTGRES_PASSWORD=devops 
    -e POSTGRES_DB=meeting_rooms 
    -v postgres_data:/var/lib/postgresql/data 
    --restart always 
    postgres:latest

  - >
    docker run -d --name seats-booking 
    --network app-network 
    -p 80:80 
    -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/meeting_rooms 
    -e SPRING_DATASOURCE_USERNAME=devops 
    -e SPRING_DATASOURCE_PASSWORD=devops 
    --restart always 
    ghcr.io/icerzack/seats-booking:latest

final_message: "The system is finally up, after $UPTIME seconds"