apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: seats-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/REPOSITORY_OWNER/seats-booking/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10101
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/meeting_rooms
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SERVER_PORT
          value: "10101"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: seats-booking
spec:
  selector:
    app: backend
  ports:
  - port: 10101
    targetPort: 10101
  type: ClusterIP 