apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seats-booking-ingress
  namespace: seats-booking
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 10101
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80 